logging:
  file:
    name: logs/serviceb.log
  level:
    root: INFO
    com.company: DEBUG

server:
  port: 8082

spring:
  application:
    name: service-b

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  feign:
    enabled: true